services:
  nginx:
    image: nginx:alpine
    user: "${UID}:${GID}"
    ports:
      - 80:80
    volumes: # 挂载 下边每行前边的`-`代表这个东西是数组的一个元素.就是说volumes属性的值是一个数组
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./site/:/site/
    # extra_hosts:
    #   - host.docker.internal:host-gateway
