FROM scratch

WORKDIR /app
# 从builder镜像中把/WebApp 拷贝到当前目录
COPY ./minioUpload-linux-arm64 /app/WebApp

# 将项目用到的静态文件拷贝到镜像（如果没有可忽略该步骤）
COPY ./config-k8s.toml /app/config.toml

# 声明服务端口
EXPOSE 7700

# 启动容器时运行的命令
CMD ["/app/WebApp","server"]
